#!/bin/bash
#SBATCH --time=00:10:00
#SBATCH -p normal64         # partition/queue
#SBATCH --job-name=toyatm   # job name
#SBATCH -N 1                # number of nodes
#SBATCH -o /scratch/work/cglo315/ESIWACE/release-4.0/tests/CPL_ORCA2_ICE_PISCES/EXP00/Log/job.out%j
#SBATCH -e /scratch/work/cglo315/ESIWACE/release-4.0/tests/CPL_ORCA2_ICE_PISCES/EXP00/Log/job.out%j
#SBATCH --exclusive

set -vx
module list


CONFIG_DIR=/scratch/work/cglo315/ESIWACE/release-4.0/tests/CPL_ORCA2_ICE_PISCES/EXP00
echo $CONFIGDIR
cd ${TMPDIR}
echo "RUN directory " `pwd`

# Get input  files
DATA1DIR=/scratch/work/cglo315/ESIWACE/initial_intrumented/cfgs/ORCA2_ICE_PISCES/EXP00/Inputs
for file in $DATA1DIR/* 
do
ln -s $file . || exit 2
done

# Get input namelist  and xml files
for file in $CONFIG_DIR/*namelist*_ref $CONFIG_DIR/*namelist*_cfg $CONFIG_DIR/*.xml
do
    cp $file . || exit 3
done

# Get data for toyatm
TOYATM_DIR=/scratch/work/cglo315/ESIWACE/release-4.0/tools/TOYATM
for file in $TOYATM_DIR/EXP/*
do
    cp $file . || exit 4
done

# Get Executables
cp $CONFIG_DIR/../BLD/bin/nemo.exe .  || exit 5
cp $TOYATM_DIR/toyatm.exe . || exit 5

echo "DIR BEFORE EXEC"
ls -l

echo 'Prepare launch of the run'
echo '----------------'

NB_PROCS_NEMO=38
NB_PROCS_TOYATM=1
#
echo 'Run the code'
echo '----------------'
time mpirun -np ${NB_PROCS_NEMO} ./nemo.exe : -np ${NB_PROCS_TOYATM} ./toyatm.exe
echo "DIR AFTER EXEC"
ls -l
date
pwd
